CREATE TABLE Countries(Id INT PRIMARY KEY, [Name] VARCHAR(50))
CREATE TABLE Towns (Id INT PRIMARY KEY,[Name] VARCHAR(50), CountryCode INT FOREIGN KEY REFERENCES Countries(Id))
CREATE TABLE Minions(Id INT PRIMARY KEY, [Name] VARCHAR(50), Age INT, TownId INT FOREIGN KEY REFERENCES Towns(Id))
CREATE TABLE EvilnessFactors(Id INT PRIMARY KEY, [Name] VARCHAR(50))
CREATE TABLE Villains(Id INT PRIMARY KEY, [Name] VARCHAR(50),EvilnessFactorId INT FOREIGN KEY REFERENCES EvilnessFactors(Id))
CREATE TABLE MinionsVillains(MinionId INT FOREIGN KEY REFERENCES Minions(Id), VillainId INT FOREIGN KEY REFERENCES Villains(Id),CONSTRAINT PK_MininonsVillains PRIMARY KEY(MinionId, VillainId))

